
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
microservice:
  doctor-service:
    endpoints:
      endpoint:
        allDoctor: http://doctor-service/doctor/all
